### PR TITLE
Changing README.rst

### LINKED ISSUE #172: Update `README.rst` file
As title says.

### PR DESCRIPTION
**Pull request by clatapie**
Closes #172

### CODE REVIEW

**Comment by clatapie** [comment]
@ansys-reviewer-bot help

**Comment by RobPasMue** [comment]
Hmmm it's weird that the "error" message shows up always at the end
I'll have to look into that

**Comment by clatapie** [comment]
> Hmmm it's weird that the "error" message shows up always at the end I'll have to look into that

Isn't it coming from the `help` call?

**Comment by RobPasMue** [comment]
> @ansys-reviewer-bot help

Ah yes, you called it here! My bad

**Pull request closed without merging**
